config/routes.rb
AppBase::Application.routes.draw do

  resources :sheet0s do
    collection do
      get 'tag'
    end
  end

  resources :efiles

  resources :attachments, :only => [:index] do
    member do
      get 'download'
    end
  end

  resources :sheets do as_routes end

  devise_for :users

  resources :main, :only => [:index] do
    collection do
      get 'search'
    end
  end

  root :to => "main#index"

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :description, :file

  belongs_to :attachable, :polymorphic => true

  mount_uploader :file, FileUploader
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  attr_accessible :code, :name, :status, :comment, :attachments_attributes

  has_many :attachments, :as => :attachable

  accepts_nested_attributes_for :attachments
end

app/models/sheet0.rb
class Sheet0 < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  searchable do
    text :f1, :boost => 2.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def download
    @rec = Attachment.find(params[:id])
    file_path = Rails.root.to_s + '/public' + @rec.file.to_s
    send_file file_path
  end
end

app/controllers/main_controller.rb
# -*- coding: utf-8 -*-
class MainController < ApplicationController
  def index
  end

  # TODO: will change Sheet0 to user's model'
  def search
    if params[:search][:key]
      @sheet0s = Sheet0.search{ fulltext params[:search][:key] }.results
    else
      render :text => '请输入搜索关键词' and return
    end

    respond_to do |format|
      format.html { render :file => 'sheet0s/index'}
      format.json { render json: @recs }
    end
  end
end

app/controllers/sheet0s_controller.rb
class Sheet0sController < ApplicationController
  def tag
    @sheet0s = Sheet0.tagged_with("#{params[:id]}")
    tag_cloud
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sheet0s }
    end

  end

  # GET /sheet0s
  # GET /sheet0s.json
  def index
    @sheet0s = Sheet0.all
    tag_cloud
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sheet0s }
    end
  end

  # GET /sheet0s/1
  # GET /sheet0s/1.json
  def show
    @sheet0 = Sheet0.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sheet0 }
    end
  end

  # GET /sheet0s/new
  # GET /sheet0s/new.json
  def new
    @sheet0 = Sheet0.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sheet0 }
    end
  end

  # GET /sheet0s/1/edit
  def edit
    @sheet0 = Sheet0.find(params[:id])
  end

  # POST /sheet0s
  # POST /sheet0s.json
  def create
    @sheet0 = Sheet0.new(params[:sheet0])

    respond_to do |format|
      if @sheet0.save
        format.html { redirect_to @sheet0, notice: 'Sheet0 was successfully created.' }
        format.json { render json: @sheet0, status: :created, location: @sheet0 }
      else
        format.html { render action: "new" }
        format.json { render json: @sheet0.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sheet0s/1
  # PUT /sheet0s/1.json
  def update
    @sheet0 = Sheet0.find(params[:id])

    respond_to do |format|
      if @sheet0.update_attributes(params[:sheet0])
        format.html { redirect_to @sheet0, notice: 'Sheet0 was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sheet0.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheet0s/1
  # DELETE /sheet0s/1.json
  def destroy
    @sheet0 = Sheet0.find(params[:id])
    @sheet0.destroy

    respond_to do |format|
      format.html { redirect_to sheet0s_url }
      format.json { head :ok }
    end
  end

  private
  def tag_cloud
    @tags = Sheet0.tag_counts_on(:tags)
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_filter :authenticate_user!

  active_scaffold :sheet do |conf|
    conf.create.multipart = true
    conf.update.multipart = true
    conf.nested.add_link "add attachment", [:attachments]
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  def menu_data
    ret = {:data => '菜单树', :attr => {:id => 'menu_data_root'}, :metadata => {:id => 'root0'}, :children => []}
    ret[:children] = User.all.collect{|r| {:data => {:title => r.email, :attr => {:href => "/sheets/#{r.id}/edit"}}}}
    ret.to_json
  end

  def get_page_position
    "p1--p2==p3 Appliction_helper:get_page_position"
  end

  def get_page_title
    @page_title.present? ? @page_title : (I18n.t(action_name) + ": " + I18n.t('activerecord.models.' + controller_name.singularize))
  end

end

app/helpers/devises_helper.rb
module DevisesHelper
  def i18n_viewer key
    I18n.t("devise.viewer.#{key}")
  rescue
    key.to_s
  end
end

app/helpers/sheet0s_helper.rb
module Sheet0sHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/layouts/_app_begin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>AppBase</title>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header><%= render "layouts/header" %></header>

app/views/layouts/_app_end.html.erb
    <footer><%= render "layouts/footer" %></footer>
  </body>

  <!-- JS loading -->
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "nested_form" %>
  <!-- jstree config -->
  <script type="text/javascript">
    function open_link(event){
      tmp_url = this.href;
      $.ajax({type: "GET", url: tmp_url, data: "id=",
              success: function(data){$("#ajax-content").html(data);}});
    };
    
    $(function() {
    $("#menu_aside").jstree({
      "json_data" : {
        "data" : <%=raw menu_data %>},
      "plugins" : [ "themes", "json_data", "ui" ]
    }).bind("select_node.jstree", function (e, data){
      alert(data.rslt.obj.data("id"));
    }).delegate('a', 'click', open_link);
    $("#menu_aside").jstree("set_theme", "apple");

    // hidden scaffold h1: use layout to set h1
    $($('#main-content h1')[0]).addClass('hidden')
    });
  </script>
</html>

app/views/layouts/_article_1.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

app/views/layouts/_footer.html.erb
Copyright 2012-2015

app/views/layouts/_header.html.erb
<hgroup>
  <h1><%= SYSTME_NAME[:company_name]%></h1>
  <h2><%= SYSTME_NAME[:system_name]%></h2>
</hgroup>

<div style="float:right;">
  <% if user_signed_in? %>
    <%= i18n_viewer('signed_in_as') %>, <%= current_user.email %> 
    <%= link_to i18n_viewer('sign_out'), destroy_user_session_path,
  :method => :delete %>
  <% else %>
    <%= link_to i18n_viewer('sign_up'), new_user_registration_path %> or    
    <%= link_to i18n_viewer('sign_in'), new_user_session_path %>    
  <% end %>    
</div>

app/views/layouts/_main.html.erb
<aside>
  <%= render "layouts/menu_aside", {:tag_value => params['t']} %>
</aside>
<article id="ajax-content">
  <section>
    <%= I18n.t('position')%>: <%= get_page_position %>
  </section>

  <h1><%= get_page_title %></h1>

  
  <section>
    action1 | action2
  </section>

  <div id="main-search">
    <%= form_tag "/main/search", :method => 'get' do %>
    <%= text_field_tag "search[key]", (params[:search].is_a?(Hash) ?
        params[:search][:key] : ''), :placeholder => '关键字' %>
    <%= submit_tag t("search") %>
    <% end %>
  </div>

  <% if notice.present? || alert.present? %>
  <section>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </section>
  <% end %>

  <section id="main-content">
    <%= yield %>
  </section>
</article>

app/views/layouts/_menu_aside.html.erb
<h1>aside1</h1>
<div id="menu_aside"></div>
<h1>aside2</h1>
<ul>
  <li><%= link_to "nav1" "#" %></li>
  <li><%= link_to "nav2" "#" %></li>
</ul>

app/views/layouts/_menu_owner.html.erb
<ul>
  <li>
    <%= link_to "未发布", "/efiles/undist" %>
  </li>
  <li>
    <%= link_to "个人1", "/efiles/tag/p1" %>
  </li>
  <li>
    <%= link_to "个人2", "/efiles/tag/p2" %>
  </li>
<ul>

app/views/layouts/application.html.erb
<%= render "layouts/app_begin" %>

<section id="main">
  <%= render devise_controller? ? "layouts/article_1" : "layouts/main" %>
</section>

<%= render "layouts/app_end" %>

app/views/layouts/layout960.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppBase</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "nested_form" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container_24">
    <div class="grid_24 header">
      <%= render "layouts/header" %>
    </div>
    <div class="grid_24 site_menu"></div>
    <div class="grid_24 channel_menu"></div>
    <div class="grid_5 left_menu">
      <%= render "layouts/menu_owner" %>
    </div>
    <div class="grid_19 right-context">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/main/index.html.erb
<p>
</p>
<p>
<%= link_to 'Common Scaffold', sheet0s_path %>: rails标准scaffold
</p>
<p>
<%= link_to 'Active Scaffold', sheets_path %>: rails标准scaffold
</p>

app/views/sheet0s/_form.html.erb
<%= form_for(@sheet0) do |f| %>
  <% if @sheet0.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sheet0.errors.count, "error") %> prohibited this sheet0 from being saved:</h2>

      <ul>
      <% @sheet0.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :f1 %><br />
    <%= f.text_field :f1 %>
  </div>
  <div class="field">
    <%= f.label :f2 %><br />
    <%= f.number_field :f2 %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sheet0s/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @sheet0 %> |
<%= link_to 'Back', sheet0s_path %>

app/views/sheet0s/index.html.erb
<h1>标准框架模板</h1>
<table>
  <tr>
    <th>F1</th>
    <th>F2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sheet0s.each do |sheet0| %>
  <tr>
    <td><%= sheet0.f1 %></td>
    <td><%= sheet0.f2 %></td>
    <td><%= link_to 'Show', sheet0 %></td>
    <td><%= link_to 'Edit', edit_sheet0_path(sheet0) %></td>
    <td><%= link_to 'Destroy', sheet0, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sheet0', new_sheet0_path %>

<article>
  <style>
    .css1 { font-size: 1.0em; }
.css2 { font-size: 1.2em; }
.css3 { font-size: 1.4em; }
.css4 { font-size: 1.6em; }
  </style>
  
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
<% end if @tags %>  
</articl>

app/views/sheet0s/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', sheet0s_path %>

app/views/sheet0s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>F1:</b>
  <%= @sheet0.f1 %>
</p>

<p>
  <b>F2:</b>
  <%= @sheet0.f2 %>
</p>


<%= link_to 'Edit', edit_sheet0_path(@sheet0) %> |
<%= link_to 'Back', sheet0s_path %>

app/views/sheet0s/tag.html.erb
<%= render :template =>  'sheet0s/index' %>